services:
    go_backend:
      build: .  # Use `build` to rebuild the image when code changes
      #image: babulal107/go-cloud-native-app:latest # Optional: Tag the image
      ports:
        - "8080:8080"
      networks:
        - "go_app_network"
      depends_on:
        - postgres_db
    postgres_db:
      image: postgres:15
      restart: always
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: user123
        POSTGRES_DB: users_db
      ports:
        - "5432:5432"
      networks:
        - "go_app_network"
      volumes:
        - db_data:/var/lib/postgresql/data
networks:
  go_app_network:
    driver: bridge
volumes:
  db_data:  # Fixed volume definition
      driver: local  # Persist MongoDB data locally